export default {
	FETCH_PACKAGE_INFO_REQUEST: 'npms/FETCH_PACKAGE_INFO_REQUEST',
	FETCH_PACKAGE_INFO_SUCCESS: 'npms/FETCH_PACKAGE_INFO_SUCCESS',
	FETCH_PACKAGE_INFO_ERROR: 'npms/FETCH_PACKAGE_INFO_ERROR',
};
